#!/bin/bash
rm -rf dist
rm -rf *.deb *.tgz
mkdir -p dist/math3d/usr/share/pycentral/python-math3d/site-packages
mkdir -p dist/math3d/usr/share/doc
bzr export dist/math3d/DEBIAN  DEBIAN
bzr  export  dist/math3d/usr/share/doc/python-math3d debian-doc
bzr  export  dist/math3d/usr/share/pycentral/python-math3d/site-packages/math3d math3d

chmod -R u=rwX,go=rX dist
chmod 755 dist/math3d/DEBIAN
chmod 755 dist/math3d/DEBIAN/postinst
chmod 755 dist/math3d/DEBIAN/prerm
fakeroot dpkg -b dist/math3d .
version=`dpkg-deb -f  python-math3d_*_all.deb Version`
thisdir=`pwd`
cd dist/math3d/usr/share/pycentral/python-math3d/site-packages/
cp $thisdir/COPYING math3d/
tar czf $thisdir/python-math3d_${version}.tgz math3d/
rm math3d/COPYING