#!/bin/bash
scp python-math3d* mlp@lind.no-ip.org:/var/www/debian/binary
ssh mlp@lind.no-ip.org 'cd /var/www/debian/ && chown -R mlp.www-data binary && dpkg-scanpackages binary /dev/null |gzip >binary/Packages.gz'
