#!/bin/bash
scp python-math3d* ml@lind.no-ip.org:/var/www/debian/binary
ssh ml@lind.no-ip.org 'cd /var/www/debian/ && chown -R ml.www-data binary && dpkg-scanpackages binary /dev/null |gzip >binary/Packages.gz'
